/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PlantasRouteImport } from './routes/plantas'
import { Route as EncomendasRouteImport } from './routes/encomendas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuquesIndexRouteImport } from './routes/buques/index'
import { Route as PlantasSlugRouteImport } from './routes/plantas.$slug'
import { Route as BuquesSlugRouteImport } from './routes/buques/$slug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantasRoute = PlantasRouteImport.update({
  id: '/plantas',
  path: '/plantas',
  getParentRoute: () => rootRouteImport,
} as any)
const EncomendasRoute = EncomendasRouteImport.update({
  id: '/encomendas',
  path: '/encomendas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuquesIndexRoute = BuquesIndexRouteImport.update({
  id: '/buques/',
  path: '/buques/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantasSlugRoute = PlantasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PlantasRoute,
} as any)
const BuquesSlugRoute = BuquesSlugRouteImport.update({
  id: '/buques/$slug',
  path: '/buques/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/encomendas': typeof EncomendasRoute
  '/plantas': typeof PlantasRouteWithChildren
  '/sobre': typeof SobreRoute
  '/buques/$slug': typeof BuquesSlugRoute
  '/plantas/$slug': typeof PlantasSlugRoute
  '/buques/': typeof BuquesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/encomendas': typeof EncomendasRoute
  '/plantas': typeof PlantasRouteWithChildren
  '/sobre': typeof SobreRoute
  '/buques/$slug': typeof BuquesSlugRoute
  '/plantas/$slug': typeof PlantasSlugRoute
  '/buques': typeof BuquesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/encomendas': typeof EncomendasRoute
  '/plantas': typeof PlantasRouteWithChildren
  '/sobre': typeof SobreRoute
  '/buques/$slug': typeof BuquesSlugRoute
  '/plantas/$slug': typeof PlantasSlugRoute
  '/buques/': typeof BuquesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/encomendas'
    | '/plantas'
    | '/sobre'
    | '/buques/$slug'
    | '/plantas/$slug'
    | '/buques/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/encomendas'
    | '/plantas'
    | '/sobre'
    | '/buques/$slug'
    | '/plantas/$slug'
    | '/buques'
  id:
    | '__root__'
    | '/'
    | '/encomendas'
    | '/plantas'
    | '/sobre'
    | '/buques/$slug'
    | '/plantas/$slug'
    | '/buques/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EncomendasRoute: typeof EncomendasRoute
  PlantasRoute: typeof PlantasRouteWithChildren
  SobreRoute: typeof SobreRoute
  BuquesSlugRoute: typeof BuquesSlugRoute
  BuquesIndexRoute: typeof BuquesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantas': {
      id: '/plantas'
      path: '/plantas'
      fullPath: '/plantas'
      preLoaderRoute: typeof PlantasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encomendas': {
      id: '/encomendas'
      path: '/encomendas'
      fullPath: '/encomendas'
      preLoaderRoute: typeof EncomendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buques/': {
      id: '/buques/'
      path: '/buques'
      fullPath: '/buques/'
      preLoaderRoute: typeof BuquesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantas/$slug': {
      id: '/plantas/$slug'
      path: '/$slug'
      fullPath: '/plantas/$slug'
      preLoaderRoute: typeof PlantasSlugRouteImport
      parentRoute: typeof PlantasRoute
    }
    '/buques/$slug': {
      id: '/buques/$slug'
      path: '/buques/$slug'
      fullPath: '/buques/$slug'
      preLoaderRoute: typeof BuquesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlantasRouteChildren {
  PlantasSlugRoute: typeof PlantasSlugRoute
}

const PlantasRouteChildren: PlantasRouteChildren = {
  PlantasSlugRoute: PlantasSlugRoute,
}

const PlantasRouteWithChildren =
  PlantasRoute._addFileChildren(PlantasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EncomendasRoute: EncomendasRoute,
  PlantasRoute: PlantasRouteWithChildren,
  SobreRoute: SobreRoute,
  BuquesSlugRoute: BuquesSlugRoute,
  BuquesIndexRoute: BuquesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
